name: Test Installer Jenkins

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y bats

      - name: Execute starService 
        run: bash ./startService.sh

      - name: Run tests
        run: bats test.bats