name: Test Installer Jenkins

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: docker:latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats
          sudo apt-get install -y shellcheck 

      - name: Run ShellCheck
        run: | 
          shellcheck startService.sh
          shellcheck stopService.sh

      - name: Execute startService
        run: bash ./startService.sh

      - name: Run tests
        run: bats test.bats