name: Test Installer Jenkins

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0-dind
        options: --privileged
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Execute starService and tests
        run: bash ./startService.sh

      - name: Run tests
        run: bats test.bats